### ISSUE TITLE
ktor

### ISSUE THREAD

**Issue by SzasznikaJanos** [actions-on-google/actions-on-google-java#1]
[Suggesion] It would be great if had    [ktor ](https://ktor.io/) integration

**Comment by yoichiro** [comment]
The current this client library does not depend any specific libraries. That is, the interface is the following:

* Input: a request body JSON string and Map<String, String> of all request headers.
* Output: a response body JSON string

I guess that the policy above should be continued to keep. Instead, I guess that it would be better if each integration implementation which is using a specific library/framework should be prepared as each boilerplate project.

**Comment by taycaldwell** [comment]
Thank you for this feature request, we will consider it.
