### ISSUE TITLE
Inconsistencies in the Action on Google Javadoc and samples

### ISSUE THREAD

**Issue by slkasisto** [actions-on-google/actions-on-google-java#10]
It was suggested that my SO question https://stackoverflow.com/questions/54878364/inconsistencies-in-the-action-on-google-javadoc-and-samples is made into a ticket here so here we go.

**Comment by taycaldwell** [comment]
Hi @slkasisto,

The method signatures for ResponseBuilder in the examples you mentioned are based on an earlier version of the library. We will update these examples to reflect the up to date method.

For your own reference, the correct method is `ResponseBuilder getResponseBuilder(ActionRequest request) `, and the examples are provided in Java, although you can use Kotlin as well if you'd like, as the library is written in Kotlin.

**Comment by slkasisto** [comment]
I've put in a patch in a local branch that reflects the above, if you want to give me access to push I'll be happy to do so.

**Comment by taycaldwell** [comment]
@slkasisto,

Feel free to submit a pull request for review, and I can take a look.

**Comment by slkasisto** [comment]
@taycaldwell I tried, but having some auth issues:

`Simeons-MBP:response simeonleyzerzon$ git push --set-upstream origin javadoc
Username for 'https://github.com': slkasisto
Password for 'https://slkasisto@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/actions-on-google/actions-on-google-java.git/'`

Not sure if I need to be set up or is it something else on my side.

**Comment by slkasisto** [comment]
Attached is a zipped branch with the change.:

[javadoc.zip](https://github.com/actions-on-google/actions-on-google-java/files/2916542/javadoc.zip)

**Comment by Fleker** [comment]
@slkasisto you'll need to fork the library, submit to slkasisto/actions-on-google-java, then you'll be able to make a pull request back to this library.

**Comment by slkasisto** [comment]
https://github.com/actions-on-google/actions-on-google-java/pull/12
