### ISSUE TITLE
Library has a binding on Log4j through SLF4J

### ISSUE THREAD

**Issue by Molyna** [actions-on-google/actions-on-google-java#14]
The library can cause a multiple binding and potentially overwrite the bindings on an application depending on it if that application doesn't use Log4j.

As per the SLF4J documentation: 
Embedded components such as libraries not only do not need to configure the underlying logging framework, they really should not do so. They should invoke SLF4J to log but should let the end-user configure the logging environment. When embedded components try to configure logging on their own, they often override the end-user's wishes. At the end of the day, it is the end-user who has to read the logs and process them. She should be the person to decide how she wants her logging configured.

**Comment by taycaldwell** [comment]
Thank you for the report, we are currently looking into this.

**Comment by zonder129** [comment]
I am having the same problem, please fix it as soon as possible! It's overriding my own logging properties and makes me really sad :(

**Comment by Molyna** [comment]
@zonder129 you should be able to exclude the usage of log4j binding.

I don't have anything to test this with myself right now but something like this for gradle should potentially do it.
`configurations {
  runtime.exclude group: "org.slf4j", module: "slf4j-log4j12"
}`

or 

`
dependencies {
  compile ('org.springframework.data:spring-data-hadoop-core:2.0.0.M4-hadoop22') {
    exclude group: "org.slf4j", name: "slf4j-log4j12"
  }
}
`

Or for Maven something like (I don't use Maven myself so this might need some work)

`
<exclusions>
        <exclusion>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-log4j12</artifactId>
        </exclusion>
      </exclusions> 
`

**Comment by zonder129** [comment]
@Molyna thank you, that is really great workaround, I totally forgot about exclude stuff. Thanks again!

**Comment by dzuluaga** [comment]
Thanks @Molyna for the suggestion. For Maven, this exclusion worked for me:

```xml
<dependency>
    <groupId>com.google.actions</groupId>
    <artifactId>actions-on-google</artifactId>
    <version>1.0.2</version>
    <exclusions>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

Also, unrelated but if you're in the path of testing on Google App Engine Standard along with Spring Boot framework, you'll need to follow steps from [Spring Boot App Engine Standard](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/springboot-appengine-standard). Here are some steps, but not limited to. So, make sure you follow steps from the link above.

**1) Use Servlet 3.1.0:** Do not include the Jetty dependencies. But you must include Servlet API dependency:

```xml
<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>javax.servlet-api</artifactId>
    <version>3.1.0</version>
    <scope>provided</scope>
</dependency>
```
**2) Remove Tomcat Starter** After excluding Tomcat, the command `./mvnw spring-boot:run` won't work anymore. You can still run Google App Engine locally by using the command `./mvnw appengine:run`. 

```
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-web</artifactId>
  <exclusions>
    <exclusion>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

**3) Exclude JUL to SLF4J Bridge**

```xml
<!-- Exclude any jul-to-slf4j -->
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>jul-to-slf4j</artifactId>
    <scope>provided</scope>
</dependency>
```

**Comment by taycaldwell** [comment]
The log4j dependency has been removed as of https://github.com/actions-on-google/actions-on-google-java/releases/tag/v1.1.0
