### ISSUE TITLE
Debugging the project

### ISSUE THREAD

**Issue by Priyankachaudhary2606** [actions-on-google/actions-on-google-java#15]
I want to know how can I debug the project to understand the flow of code & to resolve the errors. Currently I am unable to understand the flow from where it would start and how can it be used for more projects.

**Comment by taycaldwell** [comment]
Hi @Priyankachaudhary2606,

Is your question regarding how to debug the client library itself, or a project that uses the client library?

**Comment by Priyankachaudhary2606** [comment]
I want to debug the project given with the boilerplate code.

**Comment by taycaldwell** [comment]
Hi @Priyankachaudhary2606,

The boilerplate currently contains entry points for App Engine and AWS.

For debugging, if you wish to view logs, you can do so by visiting [StackDriver Logs](https://console.cloud.google.com/logs/viewer) if you deployed your app using App Engine, or [AWS CloudWatch Logs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html) if you're using AWS lambda.

You can deploy your app using Spring Boot, however you will need to set up your own entry point class for handling requests, similar to the ones we provide for App Engine and AWS.

Spring Boot has been a popular request. Thank you for the suggestion. I will look into providing an entry point for Spring Boot for the boilerplate.

Thanks,

**Comment by Priyankachaudhary2606** [comment]
@taycaldwell 
Thank you for the response, Taylor.

**Comment by Priyankachaudhary2606** [comment]
In Spring Boot, the requests are handled by Dispatcher Servlet, that we doesn't write. 
Two Doubts I have:
1. In Spring Boot, the way to enter the application is main method. So how can we use this library from there. i.e., the Intents will get identified
2. If we need to create a different entry point for App Engine then how can that be done.

Please help.

**Comment by taycaldwell** [comment]
For Spring Boot, you should have a SpringBootServletInitializer class that configures your SpringBootApplication that contains all your endpoints, such as handlePost method etc.

Similar to the entry point classes we provide for AWS and App Engine, your SpringBootApplication class can contain an instance of the class containing your intent handler methods.

When receiving a request, your entry point class will call the handleRequest method of your intent handler class.

Hope this explanation helps. If it doesn't I can try to provide examples.

**Comment by Priyankachaudhary2606** [comment]
This is helpful. But if it is possible for you then please provide the examples too.

**Comment by Priyankachaudhary2606** [comment]
@taycaldwell 
Can you share a demo project using Java/ Kotlin library with Spring Boot to make actions on google

**Comment by Fleker** [comment]
I answered a [StackOverflow question](https://stackoverflow.com/questions/55326082/how-to-create-actions-on-google-using-spring-boot-java-library/55338945#55338945) with a bootstrap class using Spring Boot.

**Comment by Priyankachaudhary2606** [comment]
@Fleker 
Thank you so much, that worked and clarified my doubt too.
