### ISSUE TITLE
Access google contacts for custom actions on google

### ISSUE THREAD

**Issue by Priyankachaudhary2606** [actions-on-google/actions-on-google-java#16]
How can I access google contacts of linked account on Google assistant. And after that how can I share that contact in parameters using dialogflow to the fulfillment.

_Scenario_ : Using my action I want to send an information to the contact of user through SMS. How can we do that???

**Comment by Fleker** [comment]
To access contacts for a user, you will need to:

1. Connect to the [Google Contacts API](https://developers.google.com/contacts/v3/)
1. In your Action, ask the user to sign-in to your OAuth service
1. Your OAuth service should use Google Sign-In with the additional Contacts OAuth scope
1. After account linking, you'll be getting an access token in your Action webhook
1. Use the access token in your Actions webhook to make API calls to the Contacts API

To get contacts as parameters in Dialogflow, you can use [built-in entities](https://cloud.google.com/dialogflow-enterprise/docs/reference/system-entities) like `@sys.given-name` or the more generic `@sys.any` in intents to capture names. You can't directly get a user's contact as a parameter, but then you'd be able to do the lookup in their contact list and manage the disambiguation.
