### ISSUE TITLE
How to make a request to a REST service from within a Dialogflow intent

### ISSUE THREAD

**Issue by fitsie007** [actions-on-google/actions-on-google-java#22]
I am trying to make a request to a REST API from within my intent, but it always throws an error:

> MalformedResponse: Failed to parse Dialogflow response into AppResponse because of empty speech response 

I am using spring-framework RestTemplate to send the request as follows.
```java
@ForIntent("process-greeting")
  public ActionResponse greetingProcessor(ActionRequest request) {
...
String givenName = (String) request.getParameter("given-name");
Greeting greeting = restTemplate.getForObject("https://fitzroi-rest-api-0525.appspot.com/rest/{name}", Greeting.class, givenName);
responseBuilder.add(greeting.getContent()); //this is a simple greeting like "Hello, Fitz"
}
```
Is this the right way to make a call to a REST service from within an Intent?
Also, how do I log custom error messages for debugging?

**Comment by taycaldwell** [comment]
Hi @fitsie007,

Our [dialog-quotes-java](https://github.com/actions-on-google/dialogflow-quotes-java) sample provides a great example on how to make requests to external APIs and URLs. You can use that as an example.

Regarding logging - You can log using SLF4J, providing any underlying implementation you wish, such as log4j. The sample mentioned above [also provides an example of this](https://github.com/actions-on-google/dialogflow-quotes-java/blob/master/src/main/java/com/example/DevRelQuotesApp.java#L97) that you can use as a reference.

**Comment by fitsie007** [comment]
Thanks @taycaldwell. I tried this approach. However, I am getting an `java.net.UnknownHostException` when I try to connect to a URL in another project. 
My actions-on-google app is in one project (https://sampleapp-3cbe2.appspot.com) on Google cloud and my REST Service is in another Google Cloud project (https://fitzroi-rest-api-0525.appspot.com).
