### ISSUE TITLE
java.net.UnknownHostException: when trying to process an appspot.com URL from an actions-on-google project 

### ISSUE THREAD

**Issue by fitsie007** [actions-on-google/actions-on-google-java#23]
This issue is with reference to [issue 22](https://github.com/actions-on-google/actions-on-google-java/issues/22).  I am getting a `java.net.UnknownHostException` when I try to parse the JSON returned by a REST service in a Google Cloud Project. 
My actions-on-google app is in one project (https://sampleapp-3cbe2.appspot.com) on Google cloud and my REST Service is in another Google Cloud project (https://fitzroi-rest-api-0525.appspot.com). Do you know of any solution to this or do you have any recommendations?

**Comment by Fleker** [comment]
Have you looked at the error message or [similar issues](https://stackoverflow.com/questions/6484275/java-net-unknownhostexception-invalid-hostname-for-server-local)?

**Comment by fitsie007** [comment]
Thanks. However, those suggestions only work when we have access to the hosts file to add a host, which I don't believe we do on the actions-on-google. 
I was able to resolve the error using the Google Cloud documentation here: https://cloud.google.com/appengine/docs/standard/java/issue-requests. It turns out that we have to turn on `urlfetch` to be able to issue certain URL requests from an app-engine app.
Here's the resulting `appengine-web.xml` file
```xml
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">
    <runtime>java8</runtime>
    <threadsafe>true</threadsafe>
    <url-stream-handler>urlfetch</url-stream-handler>
</appengine-web-app>
```
