### ISSUE TITLE
Add Session Entities

### ISSUE THREAD

**Issue by cbeaujoin** [actions-on-google/actions-on-google-java#32]
Hi,

Historically, sessions  entities were managed from the dialogflow API, now they can be created directly in the webhook :
https://groups.google.com/forum/#!msg/dialogflow-enterprise-edition-users/K-wSIgRyT90/-BkkFYLfAgAJ

In order to simplify session entity building could you had the same model as availlable with google-cloud-dialogflow (https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-dialogflow) :

It concerns the SessionEntityType class.

Then once builded it can be added to the webhook response like this : 
```
        SessionEntityType sessionEntityType = SessionEntityType.newBuilder()
                .setEntityOverrideMode(SessionEntityType.EntityOverrideMode.ENTITY_OVERRIDE_MODE_OVERRIDE)
                .setName(sessionId + "/entityTypes/" + entityName)
                .addAllEntities(entities)
                .build();

            responseBuilder.setWebhookResponse$actions_on_google(
                    Optional.ofNullable(responseBuilder.getWebhookResponse$actions_on_google())
                            .orElse(new WebhookResponse())
                            .set("sessionEntityTypes", Lists.newArrayList(sessionEntityType))
            );

```

**Comment by cbeaujoin** [comment]
Update : A documentation has been released:
[https://cloud.google.com/dialogflow/docs/entities-session#creating_session_entities_with_fulfillment](https://cloud.google.com/dialogflow/docs/entities-session#creating_session_entities_with_fulfillment)

**Comment by taycaldwell** [comment]
Support for Session Entity Types has been added in [Release v1.8.0](https://github.com/actions-on-google/actions-on-google-java/releases/tag/v1.8.0)
