### ISSUE TITLE
UserStorage doesn't persist between conversations

### ISSUE THREAD

**Issue by Topias-Pratsam** [actions-on-google/actions-on-google-java#34]
Currently UserStorage seems to not be working. It has been like this for ~2weeks and used to work in past without major changes in my code. UserStorage seems to keep the data for length of the conversation and after new conversation starts it will show as empty.

I have done the usual people have tried: enabling all actions data including Web & App also Include Chrome history and activity ... Checked user is "VERIFIED"

Also tried to run version 1.6.0 and it had the exact same problem.

It seems like people are having the same problem on nodejs version too: 
https://github.com/actions-on-google/actions-on-google-nodejs/issues/358
https://github.com/actions-on-google/actions-on-google-nodejs/issues/359

**Comment by Fleker** [comment]
See issue 358 in the other tracker.
