### ISSUE TITLE
the project not compile on android studio

### ISSUE THREAD

**Issue by milanvadgama951** [actions-on-google/actions-on-google-java#5]
after clone from github not run on studio.

**Comment by TrianReallyHard** [comment]
Could I take a look at your code?

**Comment by sarahdwyer** [comment]
@milanvadgama951 This issue will be closed unless we have more details about the errors you're facing.

**Comment by taycaldwell** [comment]
This issue will now be closed.

If you are still running into this issue, feel free to reopen and provide clarification with the following details:

1. Android Studio version
2. Method of importing the project
3. How you are compiling the code
4. What error messages are being output

Thanks,
