### ISSUE TITLE
UserId is not present in AogRequest

### ISSUE THREAD

**Issue by viniciusccarvalho** [actions-on-google/actions-on-google-java#9]
Is there a reason why the userId property is never deserialized? I was hoping to use the `userId` from a payload to index data that may come from different users of the action. 

Or maybe I'm missing something from actions on google and we should not use userIds at all

Regards

**Comment by viniciusccarvalho** [comment]
Doh, never mind: https://developers.google.com/actions/identity/user-info

**Comment by slkasisto** [comment]
My understanding from the link you provided is that it's only not available if obtained from the AppRequest, which seems to be a separate object, however Javadoc (https://actions-on-google.github.io/actions-on-google-java/) specifically advertises it available via other means, [i.e. that is bypassing ActionRequest.getAppRequest().getUser().getId()] such as ActionRequest.getUser() for example.  I still clearly see an inconsistency between the contents of the incoming request and what's available via the Java API, as detailed in https://stackoverflow.com/questions/54871395/how-to-obtain-a-user-id-and-oauth-access-token-in-dialogflow so it should be reopen IMHO.
